# -*- coding: utf-8 -*-
"""LangChain Promt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvWB1sAM93OpjHExP_0W6sYnIeVrdcgO
"""

!pip install -q langchain rouge-score pandas scikit-learn

from langchain_core.prompts import PromptTemplate, FewShotPromptTemplate
from rouge_score import rouge_scorer
from sklearn.metrics import accuracy_score
import pandas as pd
import json

"""TASK 1: ZERO-SHOT SUMMARIZATION"""

# Zero-Shot Prompt

zero_shot_prompt = PromptTemplate(
    input_variables=["text"],
    template="""
You are a Financial Analyst.

Summarize the following earnings call in 3 bullet points.

{text}
"""
)

# Mock Summarizer Function

def mock_summarizer(text):
    sentences = text.split(".")

    summary = []

    for s in sentences[:3]:
        s = s.strip()

        if s:
            summary.append(f"- {s}")

    return "\n".join(summary)

earnings_call = """
Revenue increased by 20%.
Cloud business expanded rapidly.
Operating profit improved.
Customer growth remained strong.
"""

formatted_prompt = zero_shot_prompt.format(
    text=earnings_call
)

print("\n","PROMPT:\n")
print(formatted_prompt)

print("\nSUMMARY:\n")
print(mock_summarizer(earnings_call))

"""TASK 1: FEW-SHOT SUMMARIZATION"""

examples = [

{
"text":"Revenue grew 15%. Cloud adoption increased.",
"summary":"- Revenue up\n- Cloud growth\n- Strong performance"
},

{
"text":"Expenses increased. Margins declined.",
"summary":"- Costs increased\n- Margins fell\n- Profitability impacted"
}
]

example_prompt = PromptTemplate(
    input_variables=["text","summary"],
    template="""
Text:
{text}

Summary:
{summary}
"""
)

few_shot_prompt = FewShotPromptTemplate(
    examples=examples,
    example_prompt=example_prompt,

    prefix="Learn from examples.",

    suffix="""
Text:
{text}

Summary:
""",

    input_variables=["text"]
)

test_text = """
AI products launched successfully.
Enterprise demand increased.
Revenue exceeded forecasts.
"""

print(
    few_shot_prompt.format(
        text=test_text
    )
)

print("\nGenerated Summary:\n")
print(mock_summarizer(test_text))

"""TASK 3: TICKET CLASSIFIER"""

classifier_prompt = PromptTemplate(
    input_variables=["ticket"],
    template="""
Classify the support ticket into:

Billing
Tech
Refund
General
Escalate

Ticket:
{ticket}
"""
)

def classify_ticket(ticket):

    ticket = ticket.lower()

    if "refund" in ticket:
        return "Refund"

    elif "charged" in ticket or "invoice" in ticket:
        return "Billing"

    elif "login" in ticket or "password" in ticket:
        return "Tech"

    elif "legal" in ticket:
        return "Escalate"

    elif "security" in ticket:
        return "Escalate"

    else:
        return "General"

tickets = [

"I was charged twice.",

"Unable to login.",

"Need refund immediately.",

"What are support timings?",

"Legal complaint submitted."
]

for ticket in tickets:

    print("\nTicket:", ticket)

    print(
        "Category:",
        classify_ticket(ticket)
    )

"""TASK 4: ROUGE-L EVALUATION"""

reference = """
Revenue increased due to strong cloud growth.
"""

generated = """
Revenue increased because cloud services grew.
"""

scorer = rouge_scorer.RougeScorer(
    ['rougeL'],
    use_stemmer=True
)

score = scorer.score(
    reference,
    generated
)

print(score["rougeL"])

#PROMPT LOGGING
prompt_logs = []

prompt_logs.append(
    {
        "task":"summarization",
        "prompt":formatted_prompt
    }
)

print("\n",prompt_logs)

"""EXTENSION TASK"""

#Along with category prediction, assign a confidence score between 1–5.

def classify_with_confidence(ticket):

    ticket = ticket.lower()

    if "refund" in ticket:
        return {
            "category":"Refund",
            "confidence":5
        }

    elif "charged" in ticket or "invoice" in ticket:
        return {
            "category":"Billing",
            "confidence":5
        }

    elif "login" in ticket or "password" in ticket:
        return {
            "category":"Tech",
            "confidence":4
        }

    elif "legal" in ticket or "security" in ticket:
        return {
            "category":"Escalate",
            "confidence":5
        }

    else:
        return {
            "category":"General",
            "confidence":3
        }


ticket = "Unable to login after password reset"

print(classify_with_confidence(ticket))

#Recommend resolution time based on category.
def get_sla(category):

    sla_rules = {

        "Billing":24,
        "Tech":12,
        "Refund":48,
        "General":72,
        "Escalate":4
    }

    return sla_rules[category]

#test

result = classify_with_confidence(
    "I need a refund immediately"
)

sla = get_sla(result["category"])

print("Category :", result["category"])
print("Confidence :", result["confidence"])
print("SLA Hours :", sla)

#Export CSV of 10 test tickets with model predictions vs
# ground truth labels and compute accuracy
# CREATE TEST DATASET (10 TICKETS)

import pandas as pd

df = pd.DataFrame({

    "ticket": [
        "I was charged twice for my subscription",
        "Unable to login after password reset",
        "Please refund my annual plan",
        "What are your support timings",
        "Legal complaint regarding data misuse",
        "Invoice amount is incorrect",
        "Password reset link not working",
        "Need refund for cancelled order",
        "How can I update my profile",
        "Security breach reported"
    ],

    "ground_truth": [
        "Billing",
        "Tech",
        "Refund",
        "General",
        "Escalate",
        "Billing",
        "Tech",
        "Refund",
        "General",
        "Escalate"
    ]
})

df

#Model Prediction Function (Using task 3, classifier)
# TICKET CLASSIFIER

def classify_ticket(ticket):

    ticket = ticket.lower()

    if "refund" in ticket:
        return "Refund"

    elif "charged" in ticket or "invoice" in ticket:
        return "Billing"

    elif "login" in ticket or "password" in ticket:
        return "Tech"

    elif "legal" in ticket or "security" in ticket:
        return "Escalate"

    else:
        return "General"

# GENERATE MODEL PREDICTIONS

predictions = []

for ticket in df["ticket"]:

    prediction = classify_ticket(ticket)

    predictions.append(prediction)

df["prediction"] = predictions

df

# COMPUTE ACCURACY


from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    df["ground_truth"],
    df["prediction"]
)

print(f"Accuracy: {accuracy:.2f}")

# EXPORT RESULTS TO CSV

df.to_csv(
    "ticket_predictions.csv",
    index=False
)

print("CSV exported successfully!")

# DOWNLOAD CSV FILE

from google.colab import files

files.download("ticket_predictions.csv")

