# -*- coding: utf-8 -*-
"""gan_image_generation_mnis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-OJzbONQbOTabWQtPsijj0h9ffB4o5uL
"""

# -*- coding: utf-8 -*-
"""GAN_image_generation_MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16OWesReBHqCHK8e1YxTQPnU-ync9AoAX
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# Generator Block
class Generator(nn.Module):
  def __init__(self, z_dim):
    super().__init__()
    self.model = nn.Sequential(
        nn.ConvTranspose2d(z_dim, 256, 7, 1, 0), # Input 1x1, Output 7x7
        nn.BatchNorm2d(256),
        nn.ReLU(),
        nn.ConvTranspose2d(256, 128, 4, 2, 1), # Input 7x7, Output 14x14
        nn.BatchNorm2d(128),
        nn.ReLU(),
        nn.ConvTranspose2d(128, 1, 4, 2, 1), # Input 14x14, Output 28x28
        nn.Tanh(),
    )
  def forward(self, x):
      return self.model(x)

# Discriminator Block
class Discriminator(nn.Module):
  def __init__(self):
    super().__init__()
    self.model = nn.Sequential(
        nn.Conv2d(1, 64, 4, 2, 1),
        nn.LeakyReLU(0.2),
        nn.Conv2d(64, 128, 4, 2, 1),
        nn.BatchNorm2d(128),
        nn.LeakyReLU(0.2),
        nn.Flatten(),
        nn.Linear(128*7*7, 1),
        nn.Sigmoid(),
    )

  def forward(self, x):
      return self.model(x)

device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Hyperparameters
batch_size = 128
lr = 0.002
z_dim = 100
epochs = 10

# Dataset loading

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset = datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

dataloader = DataLoader(
    dataset,
    batch_size=batch_size,
    shuffle=True
)

# Initializing loss function, generator, discriminator and optimizers
criterion = nn.BCELoss()
generator = Generator(z_dim).to(device)
discriminator = Discriminator().to(device)
optimizer_g = optim.Adam(generator.parameters(), lr=lr, betas=(0.5, 0.999))
optimizer_d = optim.Adam(discriminator.parameters(), lr=lr, betas=(0.5, 0.999))

def show_images(fake):
  img = fake.detach().cpu()[:16]
  grid = img.view(16, 28, 28)

  fig, axes = plt.subplots(4, 4, figsize=(5, 5))
  for i, ax in enumerate(axes.flatten()):
    ax.imshow(grid[i], cmap='gray')
    ax.axis('off')
  plt.show()

# Training Step
for epoch in range(epochs):
  for real, _ in dataloader:
    real = real.to(device)
    batch_size = real.size(0)

    # Training discriminator
    noise = torch.randn(batch_size, z_dim, 1, 1).to(device)
    fake = generator(noise)

    real_labels = torch.ones(batch_size, 1).to(device)
    # Label Smoothing
    real_labels = torch.ones(batch_size, 1).to(device) * 0.9

    fake_labels = torch.zeros(batch_size, 1).to(device)

    # Real Loss
    D_real = discriminator(real)
    loss_real = criterion(D_real, real_labels)

    # Fake Loss
    D_fake = discriminator(fake.detach())
    loss_fake = criterion(D_fake, fake_labels)

    # Total Loss
    loss_D = loss_real + loss_fake

    optimizer_d.zero_grad()
    loss_D.backward()
    optimizer_d.step()

    # Train Discriminator
    output = discriminator(fake)
    g_loss = criterion(output, real_labels) # wants Discriminator to think fake is real

    optimizer_g.zero_grad()
    g_loss.backward()
    optimizer_g.step()
  show_images(real)
  show_images(fake)
  print(f"Epoch [{epoch}/{epochs}], Loss D: {loss_D.item()}, Loss G: {g_loss.item()}")

"""Extension Task for GANS Generate Higher Resolution

Images: Adapt the network architecture to generate higher resolution images than 28x28, perhaps by progressively increasing the output size or using more sophisticated upsampling techniques.
"""

# Higher Resolution Generator Block (56x56)

class GeneratorHR(nn.Module):
    def __init__(self, z_dim):
        super().__init__()

        self.model = nn.Sequential(

            # Input 1x1, Output 7x7
            nn.ConvTranspose2d(z_dim, 512, 7, 1, 0),
            nn.BatchNorm2d(512),
            nn.ReLU(),

            # Input 7x7, Output 14x14
            nn.ConvTranspose2d(512, 256, 4, 2, 1),
            nn.BatchNorm2d(256),
            nn.ReLU(),

            # Input 14x14, Output 28x28
            nn.ConvTranspose2d(256, 128, 4, 2, 1),
            nn.BatchNorm2d(128),
            nn.ReLU(),

            # Input 28x28, Output 56x56
            nn.ConvTranspose2d(128, 1, 4, 2, 1),

            # Normalize output to [-1, 1]
            nn.Tanh(),
        )

    def forward(self, x):
        return self.model(x)

# Extension Task
# Higher Resolution Discriminator Block (56x56)

class DiscriminatorHR(nn.Module):
    def __init__(self):
        super().__init__()

        self.model = nn.Sequential(

            # Input 56x56, Output 28x28
            nn.Conv2d(1, 64, 4, 2, 1),
            nn.LeakyReLU(0.2),

            # Input 28x28, Output 14x14
            nn.Conv2d(64, 128, 4, 2, 1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2),

            # Input 14x14, Output 7x7
            nn.Conv2d(128, 256, 4, 2, 1),
            nn.BatchNorm2d(256),
            nn.LeakyReLU(0.2),

            nn.Flatten(),

            nn.Linear(256 * 7 * 7, 1),

            nn.Sigmoid(),
        )

    def forward(self, x):
        return self.model(x)

# Dataset loading (56x56 images)

transform_hr = transforms.Compose([
    # Resize original MNIST image from 28x28 to 56x56
    transforms.Resize((56, 56)),

    transforms.ToTensor(),

    transforms.Normalize((0.5,), (0.5,))
])

dataset_hr = datasets.MNIST(
    root='./data',
    train=True,
    download=True,
    transform=transform_hr
)

dataloader_hr = DataLoader(
    dataset_hr,
    batch_size=batch_size,
    shuffle=True
)

# Initializing loss function, generator, discriminator and optimizers

criterion = nn.BCELoss()

generator_hr = GeneratorHR(z_dim).to(device)

discriminator_hr = DiscriminatorHR().to(device)

optimizer_g_hr = optim.Adam(
    generator_hr.parameters(),
    lr=lr,
    betas=(0.5, 0.999)
)

optimizer_d_hr = optim.Adam(
    discriminator_hr.parameters(),
    lr=lr,
    betas=(0.5, 0.999)
)

# Extension Task
# Function to display 56x56 generated images

def show_hr_images(fake):

    img = fake.detach().cpu()[:16]

    grid = img.view(16, 56, 56)

    fig, axes = plt.subplots(4, 4, figsize=(8, 8))

    for i, ax in enumerate(axes.flatten()):
        ax.imshow(grid[i], cmap='gray')
        ax.axis('off')

    plt.show()

# Extension Task
# Test Generator Output

noise = torch.randn(16, z_dim, 1, 1).to(device)

fake = generator_hr(noise)

show_hr_images(fake)

print("Generated Image Shape:", fake.shape)

# Extension Training Step

for epoch in range(epochs):
    for real, _ in dataloader_hr:

        real = real.to(device)
        batch_size = real.size(0)

        # Training discriminator
        noise = torch.randn(batch_size, z_dim, 1, 1).to(device)

        fake = generator_hr(noise)

        real_labels = torch.ones(batch_size, 1).to(device)

        # Label Smoothing
        real_labels = torch.ones(batch_size, 1).to(device) * 0.9

        fake_labels = torch.zeros(batch_size, 1).to(device)

        # Real Loss
        D_real = discriminator_hr(real)
        loss_real = criterion(D_real, real_labels)

        # Fake Loss
        D_fake = discriminator_hr(fake.detach())
        loss_fake = criterion(D_fake, fake_labels)

        # Total Loss
        loss_D = loss_real + loss_fake

        optimizer_d_hr.zero_grad()
        loss_D.backward()
        optimizer_d_hr.step()

        # Train Discriminator
        output = discriminator_hr(fake)

        g_loss = criterion(
            output,
            real_labels
        )  # wants Discriminator to think fake is real

        optimizer_g_hr.zero_grad()
        g_loss.backward()
        optimizer_g_hr.step()

    show_hr_images(fake)

    print(
        f"Epoch [{epoch}/{epochs}], "
        f"Loss D: {loss_D.item()}, "
        f"Loss G: {g_loss.item()}"
    )

# Extension Task: Generate Higher Resolution Images
#
# Changes Made:
# 1. Added an extra ConvTranspose2d layer in the Generator
#    to increase output size from 28x28 to 56x56.
#
# 2. Added an extra Conv2d layer in the Discriminator
#    to process the larger 56x56 images.
#
# 3. Resized MNIST training images from 28x28 to 56x56
#    using transforms.Resize().
#
# 4. Updated visualization function to display 56x56 images.
#
# Result:
# The GAN now generates higher-resolution handwritten digits
# compared to the original 28x28 implementation.