# -*- coding: utf-8 -*-
"""message_queues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LZ6d74j3AGYIU27-G2EwIdSN1B60JcW
"""

# -*- coding: utf-8 -*-
"""
demo2_message_queues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q2PW5FgfdM3yM7EE-BC6ub4ErJYHb37q

# 📨 Demo 2 — Message Queues, Dead-Letter Queue & Health Checks
> **EY Backend Engineering Bootcamp — Day 9**

**Scenario:** The payments modernisation team needs an async pipeline. Instead of every API call blocking on a slow fraud-check, we publish payment events to a queue and let workers consume them independently. Failed messages go to a Dead-Letter Queue (DLQ) so nothing is silently lost.

---
### Learning Objectives
- Understand producer / consumer decoupling with an in-process queue (simulating RabbitMQ/Service Bus)
- Implement dead-letter queuing for persistently-failing messages
- Add FastAPI health checks that verify MQ connectivity
- Build a `/admin/dlq` inspection endpoint and `/admin/dlq/retry` replay endpoint

### 🗺️ Road Map
```
Part 1 → Install deps
Part 2 → In-memory queue (simulates RabbitMQ)
Part 3 → Producer — POST /payments publishes events
Part 4 → Consumer worker with retry + DLQ routing
Part 5 → Health check endpoints
Part 6 → Admin DLQ endpoints
Part 7 → Run & demo end-to-end flow
Extension Tasks →  RabbitMQ cloud + Azure Service Bus
```

> **Note on RabbitMQ:** Colab can't run a local RabbitMQ broker. We simulate the broker with Python's `asyncio.Queue`. In the Extension Tasks you'll swap this for a real broker (CloudAMQP free tier or Azure Service Bus).

"""

"""
## Part 1 — Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install fastapi uvicorn[standard] structlog tenacity pyngrok nest-asyncio httpx

import nest_asyncio
nest_asyncio.apply()
print('Ready')

"""---
## Part 2 — In-Memory Broker (RabbitMQ Simulation)

We model the broker as two `asyncio.Queue` objects: the main `payments` queue and a `payments.dlq` dead-letter queue. The interface mimics what `aio_pika` exposes against a real RabbitMQ.
"""

import asyncio, json, uuid, time, structlog
from dataclasses import dataclass, field
from typing import Any, Dict, Optional

structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    logger_factory=structlog.PrintLoggerFactory(),
)
log = structlog.get_logger()

@dataclass
class Message:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    body: Dict[str, Any] = field(default_factory=dict)
    delivery_count: int = 0
    dead_lettered_at: Optional[str] = None
    dead_letter_reason: Optional[str] = None

class Broker:
    """Minimal in-process broker simulating RabbitMQ queues."""

    def __init__(self):
        self.queues: Dict[str, asyncio.Queue] = {
            'payments': asyncio.Queue(),
            'payments.dlq': asyncio.Queue(),
        }
        self.stats = {'published': 0, 'consumed': 0, 'dead_lettered': 0}

    async def publish(self, queue_name: str, body: dict):
        msg = Message(body=body)
        await self.queues[queue_name].put(msg)
        self.stats['published'] += 1
        log.info('mq.published', queue=queue_name, message_id=msg.id, body=body)
        return msg.id

    async def consume(self, queue_name: str) -> Optional[Message]:
        try:
            return self.queues[queue_name].get_nowait()
        except asyncio.QueueEmpty:
            return None

    async def dead_letter(self, msg: Message, reason: str):
        msg.dead_lettered_at = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
        msg.dead_letter_reason = reason
        await self.queues['payments.dlq'].put(msg)
        self.stats['dead_lettered'] += 1
        log.warning('mq.dead_lettered', message_id=msg.id, reason=reason)

    def depth(self, queue_name: str) -> int:
        return self.queues[queue_name].qsize()

broker = Broker()
print('In-memory broker ready — queues: payments, payments.dlq')

"""---
## Part 3 — FastAPI Producer

`POST /payments` validates the payload and publishes a payment event to the queue. The response is immediate — the caller does **not** wait for fraud check or processing.
"""

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from contextlib import asynccontextmanager

class PaymentRequest(BaseModel):
    amount: float = Field(..., gt=0, description='Amount in GBP')
    currency: str = Field(default='GBP')
    account_id: str
    reference: Optional[str] = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info('app.startup', message='Connecting to broker...')
    # In production: await aio_pika.connect_robust(RABBIT_URL)
    yield
    log.info('app.shutdown', message='Disconnecting from broker...')

app = FastAPI(title='EY Payment Queue API', version='2.0.0', lifespan=lifespan)

@app.post('/payments', status_code=202)
async def enqueue_payment(payment: PaymentRequest):
    """Accept a payment and publish it to the queue. Returns immediately."""
    msg_id = await broker.publish('payments', payment.model_dump())
    return {
        'message_id': msg_id,
        'status': 'queued',
        'queue_depth': broker.depth('payments')
    }

print('Producer endpoint /payments defined')

"""---
## Part 4 — Consumer Worker with Retry + DLQ

The worker pulls messages off the queue, processes them, and:
- **ACKs** on success (message gone)
- **NACKs** on transient failure (delivery count < 3) → requeued with backoff
- **Dead-letters** on persistent failure (delivery count ≥ 3)
"""

import random

MAX_DELIVERIES = 3

async def process_payment(msg: Message) -> dict:
    """Simulate payment processing. Fails 40% of the time."""
    await asyncio.sleep(0.05)  # simulate work
    if random.random() < 0.4:
        raise ValueError(f'Processor error — fraud check timeout for {msg.body.get("account_id")}')
    return {'processed_id': str(uuid.uuid4()), 'status': 'settled'}


async def worker_tick():
    """Process one message from the queue. Call repeatedly to drain."""
    msg = await broker.consume('payments')
    if msg is None:
        return None  # queue empty

    msg.delivery_count += 1
    log.info('worker.processing',
             message_id=msg.id,
             delivery_count=msg.delivery_count,
             account=msg.body.get('account_id'))

    try:
        result = await process_payment(msg)
        broker.stats['consumed'] += 1
        log.info('worker.acked', message_id=msg.id, result=result)
        return {'acked': msg.id, 'result': result}

    except Exception as e:
        if msg.delivery_count >= MAX_DELIVERIES:
            await broker.dead_letter(msg, reason=str(e))
            return {'dead_lettered': msg.id, 'reason': str(e)}
        else:
            # NACK: re-queue for retry
            await asyncio.sleep(0.5 * msg.delivery_count)  # backoff
            await broker.queues['payments'].put(msg)
            log.warning('worker.nacked',
                        message_id=msg.id,
                        attempt=msg.delivery_count,
                        error=str(e))
            return {'nacked': msg.id, 'attempt': msg.delivery_count}


@app.get('/payments/worker')
async def drain_one():
    """Manually trigger one worker tick (for demo). In production, runs as a background task."""
    result = await worker_tick()
    if result is None:
        return {'status': 'queue_empty', 'depth': broker.depth('payments')}
    return result


print('Consumer worker + /payments/worker endpoint defined')

"""---
## Part 5 — Health Checks

Kubernetes probes need `/health/live` and `/health/ready`. The readiness check verifies the broker is reachable before accepting traffic.
"""

@app.get('/health/live')
async def liveness():
    return {'status': 'alive'}


@app.get('/health/ready')
async def readiness():
    checks = {}

    # Check broker connectivity (in-memory: always ok; swap for real AMQP check)
    try:
        _ = broker.depth('payments')  # Real impl: await connection.channel()
        checks['mq'] = 'ok'
    except Exception as e:
        checks['mq'] = f'error: {e}'

    # Stub DB check
    checks['db'] = 'ok'

    all_ok = all(v == 'ok' for v in checks.values())
    status_code = 200 if all_ok else 503

    return JSONResponse(
        content={'status': 'ready' if all_ok else 'not_ready', **checks,
                 'queue_depth': broker.depth('payments')},
        status_code=status_code
    )

print('Health endpoints defined')

"""---
## Part 6 — Admin DLQ Endpoints
"""

from fastapi import Query

@app.get('/admin/dlq')
async def inspect_dlq(limit: int = Query(default=10, le=50)):
    """Return up to `limit` messages sitting in the DLQ."""
    items = []
    # Peek without consuming
    temp = []
    while len(items) < limit:
        msg = await broker.consume('payments.dlq')
        if msg is None:
            break
        items.append({
            'id': msg.id,
            'body': msg.body,
            'delivery_count': msg.delivery_count,
            'dead_lettered_at': msg.dead_lettered_at,
            'reason': msg.dead_letter_reason
        })
        temp.append(msg)

    # Put messages back (peek semantics)
    for m in temp:
        await broker.queues['payments.dlq'].put(m)

    return {'dlq_depth': broker.depth('payments.dlq'), 'messages': items}


@app.post('/admin/dlq/retry')
async def replay_dlq(limit: int = Query(default=5, le=20)):
    """Replay up to `limit` DLQ messages back to the main payments queue."""
    replayed = []
    for _ in range(limit):
        msg = await broker.consume('payments.dlq')
        if msg is None:
            break
        msg.delivery_count = 0  # reset retries
        msg.dead_lettered_at = None
        msg.dead_letter_reason = None
        await broker.queues['payments'].put(msg)
        replayed.append(msg.id)
        log.info('dlq.replayed', message_id=msg.id)

    return {'replayed': len(replayed), 'message_ids': replayed,
            'payments_depth': broker.depth('payments')}


@app.get('/admin/stats')
async def queue_stats():
    return {
        **broker.stats,
        'payments_depth': broker.depth('payments'),
        'dlq_depth': broker.depth('payments.dlq'),
    }

print('Admin endpoints defined: /admin/dlq, /admin/dlq/retry, /admin/stats')

"""---
## Part 7 — Run & Demo End-to-End Flow
"""

NGROK_TOKEN = 'PASTE_YOUR_TOKEN_HERE'  # ← replace this

import threading, uvicorn
from pyngrok import ngrok, conf

conf.get_default().auth_token = NGROK_TOKEN

thread = threading.Thread(target=lambda: uvicorn.run(app, host='0.0.0.0', port=8001, log_level='warning'), daemon=True)
thread.start()

import time; time.sleep(2)
tunnel = ngrok.connect(8001)
BASE = tunnel.public_url

print(f'🌐 {BASE}')
print(f'   Docs:     {BASE}/docs')
print(f'   Health:   {BASE}/health/ready')
print(f'   Stats:    {BASE}/admin/stats')

import httpx

with httpx.Client() as c:
    # 1. Check health
    print('--- HEALTH ---')
    print(c.get(f'{BASE}/health/ready').json())

    # 2. Publish 5 payments
    print('\n--- PUBLISH 5 PAYMENTS ---')
    for i in range(5):
        r = c.post(f'{BASE}/payments',
                   json={'amount': (i+1)*100, 'currency': 'GBP', 'account_id': f'ACC-{i+1:03}'})
        print(f'  Payment {i+1}: {r.json()}')

    # 3. Drain the queue — some will DLQ
    print('\n--- DRAIN QUEUE (worker ticks) ---')
    for _ in range(12):  # more ticks than messages to handle retries
        r = c.get(f'{BASE}/payments/worker')
        result = r.json()
        if result.get('status') != 'queue_empty':
            print(f'  {result}')

    # 4. Show stats
    print('\n--- FINAL STATS ---')
    print(c.get(f'{BASE}/admin/stats').json())

    # 5. Inspect DLQ
    print('\n--- DLQ CONTENTS ---')
    print(json.dumps(c.get(f'{BASE}/admin/dlq').json(), indent=2))

    # 6. Replay DLQ
    print('\n--- REPLAY DLQ ---')
    print(c.post(f'{BASE}/admin/dlq/retry').json())

"""### Extension A — Real RabbitMQ via CloudAMQP *(Medium)*
Sign up for a free [CloudAMQP](https://www.cloudamqp.com/) instance and swap the in-memory broker for `aio_pika`:
```python
import aio_pika
connection = await aio_pika.connect_robust(CLOUDAMQP_URL)
channel = await connection.channel()
queue = await channel.declare_queue('payments', durable=True,
    arguments={'x-dead-letter-exchange': 'dlx', 'x-message-ttl': 86400000})
```
- Verify messages appear in the CloudAMQP management UI
- Watch the DLQ fill up when you deliberately break the processor
"""

# !pip install aio-pika

import aio_pika
import asyncio
import json

CLOUDAMQP_URL = "amqps://your_user:your_password@your-cloud-amqp-url/vhost"

class RabbitMQBroker:
    def __init__(self):
        self.connection = None
        self.channel = None

    async def connect(self):
        self.connection = await aio_pika.connect_robust(CLOUDAMQP_URL)
        self.channel = await self.connection.channel()

        # Declare queue with DLQ support
        await self.channel.declare_queue(
            "payments",
            durable=True,
            arguments={
                "x-dead-letter-exchange": "dlx",
                "x-message-ttl": 86400000
            }
        )

        await self.channel.declare_exchange("dlx", aio_pika.ExchangeType.FANOUT)
        await self.channel.declare_queue("payments.dlq", durable=True)

    async def publish(self, queue_name: str, body: dict):
        msg = aio_pika.Message(body=json.dumps(body).encode())
        await self.channel.default_exchange.publish(
            msg,
            routing_key=queue_name
        )
        return "published"

rabbit_broker = RabbitMQBroker()


@app.on_event("startup")
async def startup():
    await rabbit_broker.connect()
    print("Connected to RabbitMQ (CloudAMQP)")

@app.post("/payments", status_code=202)
async def enqueue_payment(payment: PaymentRequest):
    await rabbit_broker.publish("payments", payment.model_dump())
    return {"status": "queued (RabbitMQ)"}

"""### Extension B — Azure Service Bus *(Medium)*
Replace the broker with Azure Service Bus (free tier). Use `azure-servicebus` SDK:
```python
from azure.servicebus import ServiceBusClient, ServiceBusMessage
with ServiceBusClient.from_connection_string(SB_CONN_STR) as client:
    sender = client.get_queue_sender('payments')
    sender.send_messages(ServiceBusMessage(json.dumps(payload)))
```
Compare dead-letter handling between RabbitMQ (`x-dead-letter-exchange`) and Service Bus (built-in DLQ per queue).

"""

# !pip install azure-servicebus

from azure.servicebus import ServiceBusClient, ServiceBusMessage
import json
import os

SERVICE_BUS_CONN_STR = os.getenv("AZURE_SERVICEBUS_CONNECTION")
QUEUE_NAME = "payments"


class AzureSBBroker:
    def __init__(self):
        self.client = ServiceBusClient.from_connection_string(SERVICE_BUS_CONN_STR)

    def publish(self, payload: dict):
        with self.client:
            sender = self.client.get_queue_sender(queue_name=QUEUE_NAME)
            with sender:
                msg = ServiceBusMessage(json.dumps(payload))
                sender.send_messages(msg)

        return "sent"

#Create Broker Instance
sb_broker = AzureSBBroker()

#Test Producer (Send Message)
result = sb_broker.publish({
    "amount": 500,
    "currency": "GBP",
    "account_id": "ACC-101"
})

print(result)

from azure.servicebus import ServiceBusClient, ServiceBusMessage

def consume_messages(conn_str, queue_name):
    with ServiceBusClient.from_connection_string(conn_str) as client:
        receiver = client.get_queue_receiver(
            queue_name=queue_name,
            max_wait_time=5
        )

        with receiver:
            for msg in receiver:
                print("Recieved", str(msg))
                receiver.complete_message(msg)

consume_messages(SERVICE_BUS_CONN_STR, QUEUE_NAME)

"""| Feature          | RabbitMQ                          | Azure Service Bus      |
| ---------------- | --------------------------------- | ---------------------- |
| DLQ setup        | Manual (`x-dead-letter-exchange`) | Built-in automatically |
| Retry handling   | Custom worker logic               | Built-in retry policy  |
| Queue creation   | Manual config                     | Simple portal/API      |
| Message movement | You handle it                     | System handles it      |
| Complexity       | High                              | Low                    |
| Best use case    | Custom event routing              | Enterprise workflows   |

### Extension C — Priority Queue *(Advanced)*
RabbitMQ supports `x-max-priority`. Add a `priority` field (1–10) to `PaymentRequest`.
- High-value payments (> £10,000) should receive priority 8
- Modify the worker to process high-priority messages first
- Verify ordering with a test that publishes mixed-priority messages
"""

import asyncio
import heapq
import uuid
import random
import nest_asyncio

nest_asyncio.apply()

#Payment Model

from pydantic import BaseModel

class PaymentRequest(BaseModel):
    amount: float
    currency: str = "GBP"
    account_id: str
    priority: int = 1   # 1 (low) → 10 (high)

#Priority Queue Broker (HEAP-based)

class PriorityBroker:
    def __init__(self):
        self.heap = []  # (priority, id, payload)

    async def publish(self, payload: dict):
        priority = payload.get("priority", 1)

        # HIGH priority should come first → use negative
        heapq.heappush(self.heap, (-priority, str(uuid.uuid4()), payload))

    async def consume(self):
        if not self.heap:
            return None

        return heapq.heappop(self.heap)[2]

    def size(self):
        return len(self.heap)

#Creating broker instance

broker = PriorityBroker()
print(" Priority broker ready")

#Requirement: if amount > £10,000 → priority = 8

def assign_priority(payment: dict):
    if payment["amount"] > 10000:
        payment["priority"] = 8
    return payment

async def publish_payment(payment: dict):
    payment = assign_priority(payment)
    await broker.publish(payment)
    print("Published:", payment)

async def worker():
    while broker.size() > 0:
        msg = await broker.consume()

        priority = msg.get("priority", 1)
        account = msg.get("account_id", "UNKNOWN")
        amount = msg.get("amount", 0)

        print(f"Processing account={account} | priority={priority} | amount={amount}")

        await asyncio.sleep(0.2)

        print(" Done:", account)

test_payments = [
    {"amount": 500, "account_id": "ACC-1"},
    {"amount": 20000, "account_id": "ACC-2"},   # priority 8
    {"amount": 1500, "account_id": "ACC-3"},
    {"amount": 50000, "account_id": "ACC-4"},    # priority 8
    {"amount": 300, "account_id": "ACC-5"},
]

async def publish_all():
    for p in test_payments:
        await publish_payment(p)

await publish_all()

print("Queue size:", broker.size())

await worker()

"""### Extension D — Background Worker with Prometheus DLQ Alert *(Advanced)*
- Replace the manual `/payments/worker` endpoint with an `asyncio` background task that drains the queue continuously
- Add a Prometheus `Gauge` for DLQ depth
- Configure an alert rule: if DLQ depth > 10 for 30s, log a `CRITICAL` alert
"""

import asyncio
import threading
import time
import random
import nest_asyncio

from prometheus_client import Gauge, start_http_server

nest_asyncio.apply()

class Broker:
    def __init__(self):
        self.queue = []
        self.dlq = []

    async def publish(self, msg: dict):
        self.queue.append(msg)

    async def consume(self):
        if not self.queue:
            return None
        return self.queue.pop(0)

broker = Broker()
print("Broker initialized")

#DLQ Metric
DLQ_DEPTH = Gauge(
    "payments_dlq_depth",
    "Number of messages in DLQ"
)

async def process(msg):
    await asyncio.sleep(0.2)

    # simulate random failure
    if random.random() < 0.4:
        raise Exception("Processing failed")

    return True


async def background_worker():
    print("🚀 Worker started...")

    while True:
        msg = await broker.consume()

        if msg is None:
            await asyncio.sleep(0.5)
            continue

        try:
            print(f"Processing {msg}")
            await process(msg)
            print("✅ Success:", msg)

        except Exception as e:
            print(" Failed → DLQ:", msg)
            broker.dlq.append(msg)

        # update Prometheus metric
        DLQ_DEPTH.set(len(broker.dlq))

start_http_server(8000)
print("Prometheus running at http://localhost:8000/metrics")

def start_worker():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(background_worker())

threading.Thread(target=start_worker, daemon=True).start()

print("Background worker started")

#Produce test messages
async def produce():
    for i in range(25):
        await broker.publish({
            "id": i,
            "account": f"ACC-{i}",
            "amount": i * 100
        })
        await asyncio.sleep(0.1)

await produce()

#DLQ ALERT LOGIC (30 sec rule)
dlq_start_time = None

def check_alert():
    global dlq_start_time

    dlq_size = len(broker.dlq)

    if dlq_size > 10:
        if dlq_start_time is None:
            dlq_start_time = time.time()

        elif time.time() - dlq_start_time >= 30:
            print("CRITICAL ALERT: DLQ > 10 for 30 seconds!")
    else:
        dlq_start_time = None

#Alert monitor loop
async def monitor():
    while True:
        check_alert()
        await asyncio.sleep(2)


def start_monitor():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(monitor())

threading.Thread(target=start_monitor, daemon=True).start()

print(" Alert monitor running")

#Ckeck system status
print("Queue size:", len(broker.queue))
print("DLQ size:", len(broker.dlq))
print("Prometheus metric:", DLQ_DEPTH._value.get())


# %%
